package it.polimi.ingsw.enumerations;

public enum ClientHandlerPhase {
    WAITING_GAME_MODE,
    WAITING_NICKNAME,
    WAITING_NUMBER_OF_PLAYERS,
    WAITING_FOR_LEADER_CARDS,
    WAITING_FOR_CLIENT_RECONNECTION,
    WAITING_IN_THE_LOBBY,
    READY_TO_START
}
